name: Continuous Integration
on:
  push:
    branches: [ master ]
jobs:
  compress-extension:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Npm run build
        run: npm run build

      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r extension.zip . -i "build/*" 
          
      - uses: actions/upload-artifact@v2
        with:
          name: Extension
          path: ./extension.zip
