name: Continuous Integration
on:
  push:
  pull_request:
jobs:
  compress-extension:
    runs-on: ubuntu-latest
    steps:
      - uses: montudor/action-zip@v1
        with:
          args: zip -r extension.zip "*.*" -x "extension.zip" -x "**/*"
      - uses: actions/upload-artifact@v2
        with:
          name: Extension
          path: extension.zip
