name: Continuous Integration
on:
  push:
  pull_request:
jobs:
  compress-extension:
    runs-on: ubuntu-latest
    steps:
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r extension.zip . -i *.* -x extension.zip
      - uses: actions/upload-artifact@v2
        with:
          name: Extension
          path: extension.zip
