name: Continuous Integration
on:
  push:
    branches: [ master ]
jobs:
  compress-extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print current working dir
        run: |
          ls -la $PWD
          ls -la $GITHUB_WORKSPACE
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r extension.zip . -i manifest.json before.js after.js background.js execute.js
      - uses: actions/upload-artifact@v2
        with:
          name: Extension
          path: ./extension.zip
